timeout: 1200s
steps:
# terraform init -input=false
- name: hashicorp/terraform:light
  args:
  - init
  - -input=false
# terraform validate
- name: hashicorp/terraform:light
  args:
  - validate
# terraform plan -input=false -out=tfplan
- name: hashicorp/terraform:light
  args:
  - plan
  - -input=false
  - -out=tfplan
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/$BUILD_ID'
    paths: ['cloudbuild-tf-plan.yaml', 'tfplan']