timeout: 1200s
steps:
# terraform init -input=false
- name: hashicorp/terraform:light
  args:
  - init
  - -input=false
  - -backend-config=backend_configs/$BRANCH_NAME.tf
# terraform validate
- name: hashicorp/terraform:light
  args:
  - validate
# terraform plan -input=false -out=tfplan
- name: hashicorp/terraform:light
  args:
  - plan
  - -input=false
  - -out=tfplan
  - -var-file=env/$BRANCH_NAME.tfvars
# terraform apply -auto-approve -input=false tfplan
- name: hashicorp/terraform:light
  args:
  - apply
  - -auto-approve
  - -input=false
  - tfplan
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/apply/$BUILD_ID'
    paths: ['cloudbuild-tf-apply.yaml', 'tfplan']
  logging: CLOUD_LOGGING_ONLY