steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/terraform',
    '--build-arg=GCLOUD_VERSION=${_GCLOUD_VERSION}',
    '--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
    '--build-arg=TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}',
    '.'
    ]
- name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/terraform'
  args: ['version']
substitutions:
  _TERRAFORM_VERSION: '1.0.2' # default value
  _TERRAFORM_VERSION_SHA256SUM: '7329f887cc5a5bda4bedaec59c439a4af7ea0465f83e3c1b0f4d04951e1181f4' # default value
images: ['${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/terraform']